// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDv0Jo52LWoT5BhxjZTOMkDTiO16TmAXus',
    appId: '1:755872735042:web:79daeceef9ac7074f232db',
    messagingSenderId: '755872735042',
    projectId: 'task-organiser-bcca0',
    authDomain: 'task-organiser-bcca0.firebaseapp.com',
    storageBucket: 'task-organiser-bcca0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLP63VsMoVIlXNNUcLJaLiPaBWPMcbTDI',
    appId: '1:755872735042:android:24340119f2b0b9f3f232db',
    messagingSenderId: '755872735042',
    projectId: 'task-organiser-bcca0',
    storageBucket: 'task-organiser-bcca0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC299Xew29BzXxhMFp1ur8wsPr6ejVdymM',
    appId: '1:755872735042:ios:bf2bd7a8282ed128f232db',
    messagingSenderId: '755872735042',
    projectId: 'task-organiser-bcca0',
    storageBucket: 'task-organiser-bcca0.appspot.com',
    iosBundleId: 'com.example.taskOrganiser',
  );

}